nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Inquizitarium
            description: A platform for creating survival quests using built-in quiz generation tools.
            version: 0.1.0
    areas:
        path_patterns:
            - ^/api/
